spring:
  application:
    name: r2dbc-postgresql-example

server:
  port: 7878

logging:
  level:
    org.springframework: TRACE

datasource:
  host: localhost
  port: 5435
  database: test
  username: postgres
  password: root